# Copyright (C) 2026 kogeler
"""Distilled session knowledge: the only local state that survives artifacts-close.

A session may write any amount of scratch below ``.artifacts/fork-maintenance``.
Before it ends it distills what future agents need into one concise Markdown
record at ``knowledge/sessions/<session>.md``. ``knowledge/INDEX.md`` is the
generated session registry that agents read first; it is never edited by hand.
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import contrib

ROOT = Path("knowledge")
SESSIONS = "sessions"
INDEX = "INDEX.md"
MAX_RECORD_BYTES = 16 * 1024
MAX_SUMMARY_CHARACTERS = 240
KINDS = ("refresh", "patch", "investigation", "tooling", "ci", "package")
FIELDS = ("Date", "Kind", "Cases", "Keywords", "Summary")
SECTIONS = ("Problem", "Findings", "Changes", "Verification", "Next time")
DATE_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
INDEX_HEADER = """# Session registry

Generated by `make -C fork-maintenance knowledge-index` from `sessions/*.md`;
never edit it by hand. Search this table first (`rg -i '<symptom|symbol|case>'`),
then open only the matching session records. Records are leads, not acceptance
evidence: current source and new named results outrank them.

| Session | Date | Kind | Cases | Keywords | Summary |
| --- | --- | --- | --- | --- | --- |
"""
TEMPLATE = """# <one-line problem statement>

- Date: {date}
- Kind: <{kinds}>
- Cases: <comma-separated case slugs, or none>
- Keywords: <comma-separated symptoms, error strings, subsystems, symbols>
- Summary: <one sentence: the conclusion a future agent needs>

## Problem

<!-- Trigger, observed symptom and exact short signatures (error text, failing
test id, profile). Embedded source and develop commits. -->

## Findings

<!-- Root cause or review conclusion with path:symbol references; ownership and
failure paths that mattered; dead ends that cost time and why they failed. -->

## Changes

<!-- Cases/patches/tooling changed and why; keep/adapt/retire decisions;
resulting patch digests; what was deliberately left alone. -->

## Verification

<!-- Gates run and their outcomes, in one line each. Named runs are deleted at
close: record conclusions, never paste logs. Remaining or failed gates. -->

## Next time

<!-- Where to start, commands and oracles that helped, pitfalls, open risks and
follow-ups. -->
"""


@dataclass(frozen=True)
class Record:
    session: str
    title: str
    date: str
    kind: str
    cases: tuple[str, ...]
    keywords: tuple[str, ...]
    summary: str


def items(value: str, field: str) -> tuple[str, ...]:
    parts = tuple(part.strip() for part in value.split(","))
    if not all(parts):
        contrib.fail(f"{field} contains an empty item")
    return parts


def require_file(path: Path, description: str) -> os.stat_result:
    info = path.lstat()
    if (
        not stat.S_ISREG(info.st_mode)
        or info.st_uid != os.getuid()
        or info.st_nlink != 1
        or stat.S_IMODE(info.st_mode) & 0o002
    ):
        contrib.fail(f"{description} is not an owned, singly-linked, not other-writable file: {path}")
    return info


def parse_record(path: Path) -> Record:
    session = path.name.removesuffix(".md")
    if path.suffix != ".md" or not contrib.SLUG_RE.fullmatch(session):
        contrib.fail(f"session record name must be <lowercase-session-id>.md: {path.name}")
    if require_file(path, "session record").st_size > MAX_RECORD_BYTES:
        contrib.fail(f"session record exceeds {MAX_RECORD_BYTES} bytes; distill it: {path.name}")
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError as error:
        contrib.fail(f"session record is not UTF-8: {path.name}: {error}")
    header = 2 + len(FIELDS)
    title = lines[0][2:].strip() if lines else ""
    if len(lines) <= header or not lines[0].startswith("# ") or not title or lines[1]:
        contrib.fail(f"session record must start with '# <title>' and a blank line: {path.name}")
    if title.startswith("<") and title.endswith(">"):
        contrib.fail(f"session record title is still a placeholder: {path.name}")
    values: dict[str, str] = {}
    for number, (field, line) in enumerate(zip(FIELDS, lines[2:header], strict=True), start=3):
        prefix = f"- {field}: "
        value = line.removeprefix(prefix).strip()
        if not line.startswith(prefix) or not value:
            contrib.fail(f"session record line {number} must be '{prefix}<value>': {path.name}")
        if any(character in value for character in "|<>"):
            contrib.fail(f"session record {field} contains '|', '<' or '>': {path.name}")
        values[field] = value
    if lines[header]:
        contrib.fail(f"session record metadata must end with a blank line: {path.name}")
    date = values["Date"]
    try:
        valid_date = DATE_RE.fullmatch(date) and datetime.date.fromisoformat(date)
    except ValueError:
        valid_date = False
    if not valid_date:
        contrib.fail(f"session record Date must be YYYY-MM-DD: {path.name}")
    if values["Kind"] not in KINDS:
        contrib.fail(f"session record Kind must be one of {', '.join(KINDS)}: {path.name}")
    cases = () if values["Cases"] == "none" else items(values["Cases"], "Cases")
    if not all(contrib.SLUG_RE.fullmatch(case) for case in cases):
        contrib.fail(f"session record Cases must be case slugs or none: {path.name}")
    if len(values["Summary"]) > MAX_SUMMARY_CHARACTERS:
        contrib.fail(f"session record Summary exceeds {MAX_SUMMARY_CHARACTERS} characters: {path.name}")
    body = COMMENT_RE.sub("", "\n".join(lines[header:])).splitlines()
    headings = [index for index, line in enumerate(body) if line.startswith("## ")]
    cursor = 0
    for section in SECTIONS:
        start = next((index for index in headings if index >= cursor and body[index] == f"## {section}"), None)
        if start is None:
            contrib.fail(f"session record lacks '## {section}' (sections in order: {', '.join(SECTIONS)}): {path.name}")
        end = next((index for index in headings if index > start), len(body))
        if not any(line.strip() for line in body[start + 1 : end]):
            contrib.fail(f"session record section '## {section}' is empty: {path.name}")
        cursor = end
    return Record(
        session,
        title,
        date,
        values["Kind"],
        cases,
        items(values["Keywords"], "Keywords"),
        values["Summary"],
    )


def render_index(records: tuple[Record, ...]) -> str:
    rows = sorted(records, key=lambda record: (record.date, record.session), reverse=True)
    return INDEX_HEADER + "".join(
        f"| [{record.session}]({SESSIONS}/{record.session}.md) | {record.date} | {record.kind} | "
        f"{', '.join(record.cases) or 'none'} | {', '.join(record.keywords)} | {record.summary} |\n"
        for record in rows
    )


def inspect(state_root: Path) -> tuple[tuple[Record, ...], tuple[tuple[Path, str], ...]]:
    """Return valid records and every problem as (state-relative path, reason)."""
    root = state_root / ROOT
    if not root.exists() and not root.is_symlink():
        return (), ()
    problems: list[tuple[Path, str]] = []
    records: list[Record] = []
    try:
        contrib.require_owned_directory(root, "knowledge root", private=False)
        sessions = root / SESSIONS
        for path in sorted(root.iterdir()):
            if path.name not in {INDEX, SESSIONS}:
                problems.append((path.relative_to(state_root), f"knowledge holds only {INDEX} and {SESSIONS}/"))
        if sessions.exists() or sessions.is_symlink():
            contrib.require_owned_directory(sessions, "session record directory", private=False)
            for path in sorted(sessions.iterdir()):
                try:
                    records.append(parse_record(path))
                except (contrib.ContribError, OSError) as error:
                    problems.append((path.relative_to(state_root), str(error)))
        index = root / INDEX
        expected = render_index(tuple(records))
        if not index.exists() and not index.is_symlink():
            if records:
                problems.append((index.relative_to(state_root), "missing; run knowledge-index"))
        else:
            require_file(index, "session registry")
            if index.read_text(encoding="utf-8") != expected:
                problems.append((index.relative_to(state_root), "stale or hand-edited; run knowledge-index"))
    except (contrib.ContribError, OSError, UnicodeDecodeError) as error:
        problems.append((ROOT, str(error)))
    return tuple(records), tuple(problems)


def write_index(repo: Path) -> int:
    state_root = contrib.cleanup_state_root(repo)
    records, problems = inspect(state_root)
    blocking = [problem for problem in problems if problem[0] != ROOT / INDEX]
    if blocking:
        contrib.fail("; ".join(f"{path}: {reason}" for path, reason in blocking))
    root = state_root / ROOT
    if not root.exists():
        return 0
    descriptor, temporary = tempfile.mkstemp(dir=root, prefix=f".{INDEX}.", suffix=".partial")
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(render_index(records))
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, 0o600)
        os.replace(temporary, root / INDEX)
        contrib.fsync_directory(root)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise
    return len(records)


def new_record(repo: Path, session: str) -> Path:
    if not contrib.SLUG_RE.fullmatch(session):
        contrib.fail("SESSION must use lowercase words separated by single hyphens")
    state_root = contrib.cleanup_state_root(repo)
    contrib.require_owned_directory(state_root.parent, "artifact root")
    for directory in (state_root, state_root / ROOT, state_root / ROOT / SESSIONS):
        directory.mkdir(mode=0o700, exist_ok=True)
        contrib.require_owned_directory(directory, "knowledge directory", private=False)
    path = state_root / ROOT / SESSIONS / f"{session}.md"
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
        stream.write(TEMPLATE.format(date=datetime.date.today().isoformat(), kinds="|".join(KINDS)))
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("new", "index", "check"))
    args = parser.parse_args()
    repo = contrib.REPOSITORY_ROOT
    try:
        if args.action == "new":
            print(new_record(repo, os.environ.get("XPRA_KNOWLEDGE_SESSION", "")))
            return 0
        if args.action == "index":
            print(f"sessions={write_index(repo)}")
            return 0
        records, problems = inspect(contrib.cleanup_state_root(repo))
        for path, reason in problems:
            print(f"knowledge: {path}: {reason}", file=sys.stderr)
        print(f"sessions={len(records)}")
        print(f"knowledge={'invalid' if problems else 'valid'}")
        return 1 if problems else 0
    except (contrib.ContribError, OSError) as error:
        print(f"knowledge: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
